version: '3.4'
services:
  avado-tornadocashrelayer.public.dappnode.eth:
    image: 'avado-tornadocashrelayer.public.dappnode.eth:0.0.7'
    build: ./build
    ports:
      - '8000:8000'
      - '82:82'
    volumes:
      - 'packagedata:/packagedata'
    restart: always
volumes:
  packagedata: {}
