version: '3.4'
services:
  avado-tornadocashrelayerv2.public.dappnode.eth:
    image: 'avado-tornadocashrelayerv2.public.dappnode.eth:0.1.15'
    build: ./build
    ports:
      - '8000:8000'
      - '80:80'
    volumes:
      - 'packagedata:/packagedata'
    restart: always
volumes:
  packagedata: {}
